final Map<String, Map<String, String>> appLang = {
  'en': {
    // Shared
    'appTitle': "Panimalar Smart Transit",
    'appSubtitle': "Panimalar Engineering College",
    'langLabel': "Choose Language",
    'logout': "Logout",
    
    // Admin Shell
    'admin_overview': "Overview",
    'admin_live_tracker': "Live Tracker",
    'admin_intercom': "Intercom",
    'admin_approvals': "Approvals",
    'admin_registry': "Registry",
    'admin_subtitle': "College Administration System",
    'admin_online': "online",
    'admin_live_fleet': "Live Active Fleet",
    'admin_pending': "pending",
    'admin_pickup_queue': "Pickup Letters Queue",
    'admin_stop_capture': "DRIVER LOCATION STOP CAPTURE CONSOLE",
    'admin_allow_stops': "Allow Drivers to Add Stops",
    'admin_enable_stops_desc': "Enable to let drivers submit their current location as a new bus stop.",
    'admin_suggested_stops': "Suggested stops by Drivers (Grouped by Bus Card):",
    'admin_stops_checkins': "stops check-ins",
    'admin_active_alerts': "ACTIVE ALERTS PREVIEW",
    'admin_broadcast_notice': "Broadcast Notice",

    // Student Shell
    'student_home': "Home",
    'student_live_track': "Live Track",
    'student_campus_map': "Campus Map",
    'student_profile': "Profile",

    // Driver
    'sectionLogin': "Driver Login",
    'busNumber': "Bus Number",
    'busPassword': "Password",
    'signIn': "Sign In",
    'errorEnter': "Please enter bus number and password.",
    'errorInvalid': "Invalid bus number or password.",
    'dashboardLabel': "Driver Dashboard",
    'busLabel': "Bus Number",
    'statusLabel': "Status",
    'routeLabel': "Poonamallee Campus",
    'gpsLabel': "Live GPS Status",
    'latLabel': "Latitude",
    'lngLabel': "Longitude",
    'accLabel': "Accuracy",
    'updatedLabel': "Updated",
    'highlightTitle': "Your bus is connected to campus fleet platform.",
    'highlightText': "Start tracking to broadcast location.",
    'startTracking': "Start Tracking",
    'stopTracking': "Stop Tracking",
    'reportBreakdown': "Report Breakdown",
    'fleetLabel': "Live fleet dashboard",
    'etaTitle': "Route ETA",
    'nextStopLabel': "Next stop:",
    'healthTitle': "Vehicle health",
    'boardingTitle': "Student boarding",
    'logBoarding': "Log boarding",
    'breakdownSection': "⚠️ Breakdown Alert (Student Notification)",
    'replacementBus': "Replacement Bus Number",
    'detectedLocation': "Detected Location",
    'sendAlert': "Send Alert to Students",
    'langLabelDash': "Language",
    'trackingStopped': "Tracking stopped.",
    'trackingStarted': "Live GPS tracking started.",
    'boardingLogged': "Student boarding logged.",
    'allBoarded': "All students already boarded.",
    'replacementErrorEmpty': "Enter replacement bus number",
    'locationUnavailable': "Location not available yet",
    'alertSaved': "✅ Alert saved to Firebase",
    'bottomInfo': "Panimalar Engineering College campus transport",
    'notifyRoute': "Notify Buses on Same Route",
    'autoAlertNearby': "Auto-alert nearby buses to collect stranded students",
    'notifyExpl': "When your bus breaks down, other buses on the same route are automatically notified via Firebase to pick up your students.",
    'sendBreakdownBuses': "Send Breakdown to Route Buses",
    'speechTitle': "Speech Monitor",
    'speechWaiting': "Waiting for tracking…",
    'speechActive': "Speech monitoring active.",
    'speakingTime': "Speaking time",
    'sessions': "Sessions",
    'longest': "Longest",
    'pctDrive': "% drive time",
    'speechUsage': "Speech usage",
    'sessionLog': "Session log",
    'speechTooMuch': "⚠️ Speaking too much while driving — admin notified."
  },
  'ta': {
    // Shared
    'appTitle': "பனிமலர் ஸ்மார்ட் ட்ரான்சிட்",
    'appSubtitle': "பனிமலர் பொறியியல் கல்லூரி",
    'langLabel': "மொழியைத் தேர்வு செய்யவும்",
    'logout': "வெளியேறு",

    // Admin Shell
    'admin_overview': "கண்ணோட்டம்",
    'admin_live_tracker': "லைவ் டிராக்கர்",
    'admin_intercom': "இன்டர்காம்",
    'admin_approvals': "அனுமதிகள்",
    'admin_registry': "பதிவேடு",
    'admin_subtitle': "கல்லூரி நிர்வாக அமைப்பு",
    'admin_online': "ஆன்லைனில்",
    'admin_live_fleet': "நேரலை பஸ் நெட்வொர்க்",
    'admin_pending': "நிலுவையில்",
    'admin_pickup_queue': "அனுமதி கடிதங்கள்",
    'admin_stop_capture': "பஸ் நிறுத்தம் பதிவு பகுதி",
    'admin_allow_stops': "டிரைவர்கள் நிறுத்தங்களை சேர்க்க அனுமதிக்கவும்",
    'admin_enable_stops_desc': "டிரைவர்கள் தங்கள் தற்போதைய இடத்தை புதிய பஸ் நிறுத்தமாக சமர்ப்பிக்க இயக்கவும்.",
    'admin_suggested_stops': "டிரைவர்களால் பரிந்துரைக்கப்பட்ட நிறுத்தங்கள்:",
    'admin_stops_checkins': "நிறுத்தங்கள் பதிவு",
    'admin_active_alerts': "செயலில் உள்ள எச்சரிக்கைகள்",
    'admin_broadcast_notice': "அறிவிப்பை ஒளிபரப்பு",

    // Student Shell
    'student_home': "முகப்பு",
    'student_live_track': "நேரலை டிராக்கிங்",
    'student_campus_map': "வளாக வரைபடம்",
    'student_profile': "சுயவிவரம்",

    // Driver
    'sectionLogin': "டிரைவர் உள்நுழைவு",
    'busNumber': "பஸ் எண்",
    'busPassword': "கடவுச்சொல்",
    'signIn': "உள்நுழை",
    'errorEnter': "பஸ் எண் மற்றும் கடவுச்சொல்லை உள்ளிடவும்.",
    'errorInvalid': "தவறான பஸ் எண் அல்லது கடவுச்சொல்.",
    'dashboardLabel': "டிரைவர் டேஷ்போர்டு",
    'busLabel': "பஸ் எண்",
    'statusLabel': "நிலை",
    'routeLabel': "பூந்தமல்லி வளாகம்",
    'gpsLabel': "நேரலை GPS நிலை",
    'latLabel': "அட்சரேகை",
    'lngLabel': "தீர்க்கரேகை",
    'accLabel': "துல்லியம்",
    'updatedLabel': "புதுப்பிக்கப்பட்டது",
    'highlightTitle': "உங்கள் பஸ் வளாக போக்குவரத்து நெட்வொர்க்குடன் இணைக்கப்பட்டுள்ளது.",
    'highlightText': "இடத்தை பகிர டிராக்கிங் தொடங்கவும்.",
    'startTracking': "டிராக்கிங் தொடங்கு",
    'stopTracking': "டிராக்கிங் நிறுத்து",
    'reportBreakdown': "பழுது எச்சரிக்கை",
    'fleetLabel': "நேரலை கடற்படை டேஷ்போர்டு",
    'etaTitle': "வழி வருகை நேரம் (ETA)",
    'nextStopLabel': "அடுத்த நிறுத்தம்:",
    'healthTitle': "வாகன ஆரோக்கியம்",
    'boardingTitle': "மாணவர் ஏறுதல்",
    'logBoarding': "ஏறுதல் பதிவு",
    'breakdownSection': "⚠️ பஸ் பழுது எச்சரிக்கை",
    'replacementBus': "மாற்று பஸ் எண்",
    'detectedLocation': "கண்டறியப்பட்ட இடம்",
    'sendAlert': "மாணவர்களுக்கு எச்சரிக்கை அனுப்பு",
    'langLabelDash': "மொழி",
    'trackingStopped': "டிராக்கிங் நிறுத்தப்பட்டது.",
    'trackingStarted': "நேரலை GPS டிராக்கிங் தொடங்கப்பட்டது.",
    'boardingLogged': "மாணவர் ஏறுதல் பதிவு செய்யப்பட்டது.",
    'allBoarded': "அனைத்து மாணவர்களும் ஏற்கனவே ஏறிவிட்டனர்.",
    'replacementErrorEmpty': "மாற்று பஸ் எண்ணை உள்ளிடவும்",
    'locationUnavailable': "இடம் இன்னும் கிடைக்கவில்லை",
    'alertSaved': "✅ எச்சரிக்கை சேமிக்கப்பட்டது",
    'bottomInfo': "பனிமலர் பொறியியல் கல்லூரி வளாக போக்குவரத்து",
    'notifyRoute': "ஒரே வழியில் செல்லும் பேருந்துகளுக்கு அறிவிக்கவும்",
    'autoAlertNearby': "அருகிலுள்ள பேருந்துகளை தானாக எச்சரிக்கவும்",
    'notifyExpl': "உங்கள் பேருந்து பழுதடைந்தால், அதே வழியில் உள்ள மற்ற பேருந்துகளுக்கு தானாகவே அறிவிக்கப்பட்டு மாணவர்களை அழைத்துச் செல்லும்.",
    'sendBreakdownBuses': "பேருந்துகளுக்கு பழுது அறிவிப்பை அனுப்பு",
    'speechTitle': "பேச்சு மானிட்டர்",
    'speechWaiting': "டிராக்கிங்கிற்காக காத்திருக்கிறது...",
    'speechActive': "பேச்சு கண்காணிப்பு செயலில் உள்ளது.",
    'speakingTime': "பேசும் நேரம்",
    'sessions': "அமர்வுகள்",
    'longest': "நீண்ட நேரம்",
    'pctDrive': "% ஓட்டுநர் நேரம்",
    'speechUsage': "பேச்சு பயன்பாடு",
    'sessionLog': "அமர்வு பதிவு",
    'speechTooMuch': "⚠️ வாகனம் ஓட்டும்போது அதிகமாகப் பேசுகிறார் — நிர்வாகிக்கு அறிவிக்கப்பட்டது.",
    "🚌 Bus is on the way. Please be ready at your stop.": "🚌 பஸ் வந்துகொண்டிருக்கிறது. உங்கள் நிறுத்தத்தில் தயாராக இருங்கள்.",
    "⏱️ Slight delay due to traffic. ETA 10 minutes.": "⏱️ போக்குவரத்து நெரிசலால் தாமதம். வருகை நேரம் 10 நிமிடங்கள்.",
    "✅ Bus has arrived at campus safely.": "✅ பஸ் பாதுகாப்பாக வளாகத்தை அடைந்தது.",
    "🛣️ Route is clear, proceeding as scheduled.": "🛣️ வழி தெளிவாக உள்ளது, திட்டமிட்டபடி செல்கிறது.",
    "⚠️ Emergency: Bus breakdown. Sending help.": "⚠️ அவசரம்: பஸ் பழுது. உதவி அனுப்பப்படுகிறது.",
    "🔁 Bus is returning after drop-off.": "🔁 இறக்கிவிட்ட பின் பஸ் திரும்புகிறது.",
    "⛽ Fuel stop needed. 5-minute halt.": "⛽ எரிபொருள் நிரப்ப 5 நிமிட நிறுத்தம்.",
    "🌧️ Slow speed due to rain. Be patient.": "🌧️ மழை காரணமாக வேகம் குறைவு. பொறுத்திருக்கவும்.",
    "🚫 Bus is full. Cannot board more students.": "🚫 பஸ் நிரம்பிவிட்டது. மேலும் மாணவர்களை ஏற்ற முடியாது.",
    "📍 Arriving at first stop in 5 minutes.": "📍 5 நிமிடங்களில் முதல் நிறுத்தத்தை அடையும்.",
    "🚧 Road block ahead. Taking alternate route.": "🚧 முன்னால் சாலை மறியல். மாற்று வழியில் செல்கிறது.",
    "🛑 Bus stopped for a quick headcount.": "🛑 எண்ணிக்கை சரிபார்க்க பஸ் நிறுத்தப்பட்டுள்ளது.",
    "🎓 All students safely dropped at campus.": "🎓 மாணவர்கள் அனைவரும் பாதுகாப்பாக வளாகத்தில் இறக்கிவிடப்பட்டனர்.",
    "📞 Please call admin for urgent matters.": "📞 அவசர உதவிக்கு நிர்வாகியை தொடர்பு கொள்ளவும்.",
    "🔧 Minor mechanical issue. Will resume shortly.": "🔧 சிறிய இயந்திரக் கோளாறு. விரைவில் சரிசெய்யப்படும்.",
    "🅿️ Parked at designated bus bay.": "🅿️ பஸ் நிறுத்தத்தில் நிறுத்தப்பட்டுள்ளது.",
    "👨‍🎓 Students boarding at current stop.": "👨‍🎓 மாணவர்கள் தற்போது பஸ்ஸில் ஏறிக்கொண்டிருக்கிறார்கள்.",
    "🚦 Waiting at traffic signal. On schedule.": "🚦 சிக்னலில் காத்திருக்கிறது. சரியான நேரத்தில் செல்லும்.",
    "🏫 Reached college gate. Please exit safely.": "🏫 கல்லூரி வாயிலை அடைந்தது. பாதுகாப்பாக இறங்கவும்.",
    "✔️ Trip completed. Bus returning to depot.": "✔️ பயணம் முடிந்தது. பஸ் பணிமனைக்குத் திரும்புகிறது.",
    "Bus ": "பஸ் ",
    "Breakdown": "பழுது",
    "Ready": "தயார்",
    "Replacement Bus ": "மாற்று பஸ் ",
    "is dispatched. Stay at your stop.": "அனுப்பப்பட்டுள்ளது. உங்கள் நிறுத்தத்திலேயே இருக்கவும்.",
    "The bus is now starts the journey.": "பஸ் இப்போது பயணத்தை தொடங்குகிறது.",
    "Vehicle Breakdown Alert": "வாகன பழுது எச்சரிக்கை",
    "Live": "நேரலை",
    "breakdown reported. Replacement Bus dispatch is pending. Stay at your stop.": "பழுது பதிவாகியுள்ளது. மாற்று பஸ் அனுப்பப்படுவது நிலுவையில் உள்ளது. உங்கள் நிறுத்தத்திலேயே இருக்கவும்.",
    "breakdown. Replacement Bus ": "பழுது. மாற்று பஸ் ",
    " dispatched. Stay at your stop.": " அனுப்பப்பட்டுள்ளது. உங்கள் நிறுத்தத்திலேயே இருக்கவும்.",
    "Select Predefined Intercom Message": "முன்பே வரையறுக்கப்பட்ட இன்டர்காம் செய்தியைத் தேர்ந்தெடுக்கவும்",
  },
  'te': {
    // Shared
    'appTitle': "పనిమలర్ స్మార్ట్ ట్రాన్సిట్",
    'appSubtitle': "పనిమలర్ ఇంజనీరింగ్ కళాశాల",
    'langLabel': "భాషను ఎంచుకోండి",
    'logout': "లాగ్ అవుట్",

    // Admin Shell
    'admin_overview': "అవలోకనం",
    'admin_live_tracker': "లైవ్ ట్రాకర్",
    'admin_intercom': "ఇంటర్‌కామ్",
    'admin_approvals': "ఆమోదాలు",
    'admin_registry': "రిజిస్ట్రీ",
    'admin_subtitle': "కళాశాల పరిపాలన వ్యవస్థ",
    'admin_online': "ఆన్‌లైన్",
    'admin_live_fleet': "లైవ్ బస్ నెట్‌వర్క్",
    'admin_pending': "పెండింగ్",
    'admin_pickup_queue': "అనుమతి లేఖలు",
    'admin_stop_capture': "బస్ స్టాప్ రికార్డింగ్ కన్సోల్",
    'admin_allow_stops': "స్టాప్‌లను జోడించడానికి డ్రైవర్‌లను అనుమతించండి",
    'admin_enable_stops_desc': "కొత్త బస్ స్టాప్‌గా డ్రైవర్లు తమ ప్రస్తుత స్థానాన్ని సమర్పించడానికి అనుమతించండి.",
    'admin_suggested_stops': "డ్రైవర్లు సూచించిన స్టాప్‌లు:",
    'admin_stops_checkins': "స్టాప్‌ల చెక్-ఇన్‌లు",
    'admin_active_alerts': "క్రియాశీల హెచ్చరికలు",
    'admin_broadcast_notice': "ప్రకటన ప్రసారం చేయండి",

    // Student Shell
    'student_home': "హోమ్",
    'student_live_track': "లైవ్ ట్రాక్",
    'student_campus_map': "క్యాంపస్ మ్యాప్",
    'student_profile': "ప్రొఫైల్",

    // Driver
    'sectionLogin': "డ్రైవర్ లాగిన్",
    'busNumber': "బస్సు సంఖ్య",
    'busPassword': "పాస్ వర్డ్",
    'signIn': "లాగిన్",
    'errorEnter': "బస్సు సంఖ్య మరియు పాస్ వర్డ్ నమోదు చేయండి.",
    'errorInvalid': "చెల్లని బస్సు సంఖ్య లేదా పాస్ వర్డ్.",
    'dashboardLabel': "డ్రైవర్ డాష్ బోర్డ్",
    'busLabel': "బస్సు సంఖ్య",
    'statusLabel': "స్థితి",
    'routeLabel': "పూనమల్లి క్యాంపస్",
    'gpsLabel': "లైవ్ GPS స్థితి",
    'latLabel': "అక్షాంశం",
    'lngLabel': "రేఖాంశం",
    'accLabel': "ఖచ్చితత్వం",
    'updatedLabel': "నవీకరించబడింది",
    'highlightTitle': "మీ బస్సు క్యాంపస్ రవాణా నెట్ వర్క్ తో అనుసంధానించబడింది.",
    'highlightText': "స్థానాన్ని పంచుకోవడానికి ట్రాకింగ్ ప్రారంభించండి.",
    'startTracking': "ట్రాకింగ్ ప్రారంభించు",
    'stopTracking': "ట్రాకింగ్ ఆపివేయి",
    'reportBreakdown': "బ్రేక్ డౌన్ నివేదించు",
    'fleetLabel': "లైవ్ ఫ్లీట్ డాష్ బోర్డ్",
    'etaTitle': "మార్గం ETA",
    'nextStopLabel': "తదుపరి స్టాప్:",
    'healthTitle': "వాహన ఆరోగ్యం",
    'boardingTitle': "విద్యార్థుల బోర్డింగ్",
    'logBoarding': "బోర్డింగ్ నమోదు",
    'breakdownSection': "⚠️ బస్సు బ్రేక్ డౌన్ అలర్ట్",
    'replacementBus': "ప్రత్యామ్నాయ బస్సు సంఖ్య",
    'detectedLocation': "గుర్తించిన స్థానం",
    'sendAlert': "విద్యార్థులకు అలర్ట్ పంపండి",
    'langLabelDash': "భాష",
    'trackingStopped': "ట్రాకింగ్ ఆపివేయబడింది.",
    'trackingStarted': "లైవ్ GPS ట్రాకింగ్ ప్రారంభమైంది.",
    'boardingLogged': "విద్యార్థి బోర్డింగ్ నమోదైంది.",
    'allBoarded': "విద్యార్థులందరూ ఇప్పటికే బస్సు ఎక్కారు.",
    'replacementErrorEmpty': "ప్రత్యామ్నాయ బస్సు సంఖ్యను నమోదు చేయండి",
    'locationUnavailable': "స్థానం ఇంకా అందుబాటులో లేదు",
    'alertSaved': "✅ అలర్ట్ సేవ్ చేయబడింది",
    'bottomInfo': "పనిమలర్ ఇంజనీరింగ్ కళాశాల క్యాంపస్ రవాణా",
    'notifyRoute': "అదే మార్గంలో వెళ్లే బస్సులకు తెలియజేయండి",
    'autoAlertNearby': "సమీపంలోని బస్సులను ఆటోమేటిక్ గా అలర్ట్ చేయండి",
    'notifyExpl': "మీ బస్సు బ్రేక్ డౌన్ అయినప్పుడు, అదే మార్గంలో ఉన్న ఇతర బస్సులకు విద్యార్థులను తీసుకెళ్లడానికి ఆటోమేటిక్ గా తెలియజేయబడుతుంది.",
    'sendBreakdownBuses': "బస్సులకు బ్రేక్ డౌన్ అలర్ట్ పంపండి",
    'speechTitle': "స్పీచ్ మానిటర్",
    'speechWaiting': "ట్రాకింగ్ కోసం నిరీక్షణ...",
    'speechActive': "స్పీచ్ మానిటరింగ్ సక్రియంగా ఉంది.",
    'speakingTime': "మాట్లాడే సమయం",
    'sessions': "సెషన్లు",
    'longest': "అత్యధిక సమయం",
    'pctDrive': "% డ్రైవింగ్ సమయం",
    'speechUsage': "స్పీచ్ వినియోగం",
    'sessionLog': "సెషన్ లాగ్",
    'speechTooMuch': "⚠️ డ్రైవింగ్ చేస్తున్నప్పుడు ఎక్కువగా మాట్లాడుతున్నారు — అడ్మిన్ కు తెలియజేయబడింది.",
    "Bus ": "బస్సు ",
    "Breakdown": "బ్రేక్‌డౌన్",
    "Ready": "సిద్ధంగా ఉంది",
    "Replacement Bus ": "ప్రత్యామ్నాయ బస్సు ",
    "is dispatched. Stay at your stop.": "పంపబడింది. మీ స్టాప్ వద్దే ఉండండి.",
    "The bus is now starts the journey.": "బస్సు ఇప్పుడు ప్రయాణాన్ని ప్రారంభిస్తుంది.",
    "Vehicle Breakdown Alert": "వాహన బ్రేక్‌డౌన్ అలర్ట్",
    "Live": "లైవ్",
    "breakdown reported. Replacement Bus dispatch is pending. Stay at your stop.": "బ్రేక్‌డౌన్ నివేదించబడింది. ప్రత్యామ్నాయ బస్సు పంపడం పెండింగ్‌లో ఉంది. మీ స్టాప్ వద్దే ఉండండి.",
    "breakdown. Replacement Bus ": "బ్రేక్‌డౌన్. ప్రత్యామ్నాయ బస్సు ",
    " dispatched. Stay at your stop.": " పంపబడింది. మీ స్టాప్ వద్దే ఉండండి.",
    "🚌 Bus is on the way. Please be ready at your stop.": "🚌 బస్సు వస్తోంది. దయచేసి మీ స్టాప్ వద్ద సిద్ధంగా ఉండండి.",
    "⏱️ Slight delay due to traffic. ETA 10 minutes.": "⏱️ ట్రాఫిక్ కారణంగా ఆలస్యం. 10 నిమిషాల్లో చేరుకుంటుంది.",
    "✅ Bus has arrived at campus safely.": "✅ బస్సు క్యాంపస్‌కు సురక్షితంగా చేరుకుంది.",
    "🛣️ Route is clear, proceeding as scheduled.": "🛣️ మార్గం క్లియర్‌గా ఉంది, షెడ్యూల్ ప్రకారం వెళ్తోంది.",
    "⚠️ Emergency: Bus breakdown. Sending help.": "⚠️ అత్యవసరం: బస్సు బ్రేక్‌డౌన్. సహాయం పంపబడుతోంది.",
    "🔁 Bus is returning after drop-off.": "🔁 డ్రాప్ చేసిన తర్వాత బస్సు తిరిగి వస్తోంది.",
    "⛽ Fuel stop needed. 5-minute halt.": "⛽ ఇంధనం కోసం 5 నిమిషాల నిలుపుదల.",
    "🌧️ Slow speed due to rain. Be patient.": "🌧️ వర్షం కారణంగా తక్కువ వేగం. దయచేసి ఓపిక పట్టండి.",
    "🚫 Bus is full. Cannot board more students.": "🚫 బస్సు నిండిపోయింది. మరికొంత మందిని ఎక్కించుకోలేము.",
    "📍 Arriving at first stop in 5 minutes.": "📍 5 నిమిషాల్లో మొదటి స్టాప్‌కు చేరుకుంటుంది.",
    "🚧 Road block ahead. Taking alternate route.": "🚧 ముందు రోడ్ బ్లాక్. ప్రత్యామ్నాయ మార్గంలో వెళ్తోంది.",
    "🛑 Bus stopped for a quick headcount.": "🛑 హెడ్‌కౌంట్ కోసం బస్సు ఆపబడింది.",
    "🎓 All students safely dropped at campus.": "🎓 విద్యార్థులందరూ సురక్షితంగా క్యాంపస్‌లో డ్రాప్ చేయబడ్డారు.",
    "📞 Please call admin for urgent matters.": "📞 అత్యవసర విషయాల కోసం దయచేసి అడ్మిన్‌కు కాల్ చేయండి.",
    "🔧 Minor mechanical issue. Will resume shortly.": "🔧 చిన్న యాంత్రిక లోపం. త్వరలో పరిష్కరించబడుతుంది.",
    "🅿️ Parked at designated bus bay.": "🅿️ బస్సు పార్క్ చేయబడింది.",
    "👨‍🎓 Students boarding at current stop.": "👨‍🎓 విద్యార్థులు ప్రస్తుతం ఎక్కుతున్నారు.",
    "🚦 Waiting at traffic signal. On schedule.": "🚦 ట్రాఫిక్ సిగ్నల్ వద్ద వేచి ఉంది. షెడ్యూల్ ప్రకారమే ఉంది.",
    "🏫 Reached college gate. Please exit safely.": "🏫 కళాశాల గేటుకు చేరుకుంది. దయచేసి సురక్షితంగా దిగండి.",
    "✔️ Trip completed. Bus returning to depot.": "✔️ ట్రిప్ పూర్తయింది. బస్సు డిపోకు తిరిగి వస్తోంది.",
    "Select Predefined Intercom Message": "ముందుగా అనుకున్న ఇంటర్‌కామ్ సందేశాన్ని ఎంచుకోండి",
  }
};
