import 'package:latlong2/latlong.dart';

final Map<String, List<String>> routeStopsConfig = {
  'route_15': [
    "MANALI", "M.G.R NAGAR", "IIND MAIN ROAD", "MATHUR GATE",
    "MADHAVARAM MILK COLONY", "ARUL NAGAR", "THAPAL PETTI",
    "MADHAVARAM PUTHU KOVIL", "MADHAVARAM BUS STAND",
    "MADHAVARAM SMALL ROUNDNA", "RETTRI R T O OFFICE", "COLLEGE"
  ],
  'route_52': [
    "PADAPPAI", "MANNIVAKKAM", "MUDICHUR", "PERUGALATHUR (OLD)",
    "SUNNAMBU KALVAI", "KRISHNA NAGAR", "TAMBARAM DEPOT",
    "SARAVANA STORE", "PALLAVARAM", "PAMMAL", "ANAGAPUTHUR",
    "AANDAN KUPPAM", "COLLEGE"
  ],
  'route_137': [
    "PORUR", "RETEERI", "IYYAPANTHANGAL", "KATTUPAKKAM",
    "KUMANANCHAVADI", "ARAVIND EYE HOSPITAL", "COLLEGE"
  ]
};

final Map<String, String> routeLabelsConfig = {
  'route_15': "Route 15 - Manali 2",
  'route_52': "Route 52 - Padappai",
  'route_137': "Route 137 - Porur",
};

final Map<String, String> routeColorsConfig = {
  'route_15': '#2563EB', // Blue
  'route_52': '#22C55E', // Green
  'route_137': '#F97316', // Orange
};

final Map<String, LatLng> coordsConfig = {
  // Shared
  "COLLEGE": const LatLng(13.0489049, 80.0754642),
  "Panimalar Engineering College": const LatLng(13.0489049, 80.0754642),
  
  // Route 15 stops
  "MANALI": const LatLng(13.1648, 80.2558),
  "M.G.R NAGAR": const LatLng(13.1590, 80.2460),
  "IIND MAIN ROAD": const LatLng(13.1530, 80.2410),
  "MATHUR GATE": const LatLng(13.1495, 80.2375),
  "MADHAVARAM MILK COLONY": const LatLng(13.1460, 80.2300),
  "ARUL NAGAR": const LatLng(13.1380, 80.2220),
  "THAPAL PETTI": const LatLng(13.1320, 80.2180),
  "MADHAVARAM PUTHU KOVIL": const LatLng(13.1275, 80.2120),
  "MADHAVARAM BUS STAND": const LatLng(13.1250, 80.2100),
  "MADHAVARAM SMALL ROUNDNA": const LatLng(13.1180, 80.2050),
  "RETTRI R T O OFFICE": const LatLng(13.1090, 80.2010),

  // Route 52 stops
  "PADAPPAI": const LatLng(12.8914, 80.0178),
  "MANNIVAKKAM": const LatLng(12.9050, 80.0380),
  "MUDICHUR": const LatLng(12.9180, 80.0550),
  "PERUGALATHUR (OLD)": const LatLng(12.9280, 80.0820),
  "SUNNAMBU KALVAI": const LatLng(12.9350, 80.0950),
  "KRISHNA NAGAR": const LatLng(12.9420, 80.1150),
  "TAMBARAM DEPOT": const LatLng(12.9230, 80.1200),
  "SARAVANA STORE": const LatLng(12.9550, 80.1410),
  "PALLAVARAM": const LatLng(12.9675, 80.1496),
  "PAMMAL": const LatLng(12.9807, 80.0935),
  "ANAGAPUTHUR": const LatLng(12.9900, 80.1000),
  "AANDAN KUPPAM": const LatLng(13.0100, 80.0850),

  // Route 137 stops
  "PORUR": const LatLng(13.0381, 80.1576),
  "RETEERI": const LatLng(13.0360, 80.1480),
  "IYYAPANTHANGAL": const LatLng(13.0370, 80.1385),
  "KATTUPAKKAM": const LatLng(13.0453, 80.1215),
  "KUMANANCHAVADI": const LatLng(13.0460, 80.1100),
  "ARAVIND EYE HOSPITAL": const LatLng(13.0510, 80.1010),
};

final Map<String, Map<String, String>> driverLang = {
  'en': {
    'appTitle': "Driver App",
    'appSubtitle': "Panimalar Engineering College",
    'langLabel': "Choose Language",
    'sectionLogin': "Driver Login",
    'busNumber': "Bus Number",
    'busPassword': "Password",
    'signIn': "Sign In",
    'errorEnter': "Please enter bus number and password.",
    'errorInvalid': "Invalid bus number or password.",
    'dashboardLabel': "Driver Dashboard",
    'busLabel': "Bus Number",
    'statusLabel': "Status",
    'routeLabel': "Poonamallee Campus",
    'gpsLabel': "Live GPS Status",
    'latLabel': "Latitude",
    'lngLabel': "Longitude",
    'accLabel': "Accuracy",
    'updatedLabel': "Updated",
    'highlightTitle': "Your bus is connected to campus fleet platform.",
    'highlightText': "Start tracking to broadcast location.",
    'startTracking': "Start Tracking",
    'stopTracking': "Stop Tracking",
    'reportBreakdown': "Report Breakdown",
    'fleetLabel': "Live fleet dashboard",
    'etaTitle': "Route ETA",
    'nextStopLabel': "Next stop:",
    'healthTitle': "Vehicle health",
    'boardingTitle': "Student boarding",
    'logBoarding': "Log boarding",
    'breakdownSection': "⚠️ Breakdown Alert (Student Notification)",
    'replacementBus': "Replacement Bus Number",
    'detectedLocation': "Detected Location",
    'sendAlert': "Send Alert to Students",
    'langLabelDash': "Language",
    'logout': "Logout",
    'trackingStopped': "Tracking stopped.",
    'trackingStarted': "Live GPS tracking started.",
    'boardingLogged': "Student boarding logged.",
    'allBoarded': "All students already boarded.",
    'replacementErrorEmpty': "Enter replacement bus number",
    'locationUnavailable': "Location not available yet",
    'alertSaved': "✅ Alert saved to Firebase",
    'bottomInfo': "Panimalar Engineering College campus transport",
    'notifyRoute': "Notify Buses on Same Route",
    'autoAlertNearby': "Auto-alert nearby buses to collect stranded students",
    'notifyExpl': "When your bus breaks down, other buses on the same route are automatically notified via Firebase to pick up your students.",
    'sendBreakdownBuses': "Send Breakdown to Route Buses",
    'speechTitle': "Speech Monitor",
    'speechWaiting': "Waiting for tracking…",
    'speechActive': "Speech monitoring active.",
    'speakingTime': "Speaking time",
    'sessions': "Sessions",
    'longest': "Longest",
    'pctDrive': "% drive time",
    'speechUsage': "Speech usage",
    'sessionLog': "Session log",
    'speechTooMuch': "⚠️ Speaking too much while driving — admin notified."
  },
  'ta': {
    'appTitle': "டிரைவர் ஆப்",
    'appSubtitle': "பனிமலர் பொறியியல் கல்லூரி",
    'langLabel': "மொழியைத் தேர்வு செய்யவும்",
    'sectionLogin': "டிரைவர் உள்நுழைவு",
    'busNumber': "பஸ் எண்",
    'busPassword': "கடவுச்சொல்",
    'signIn': "உள்நுழை",
    'errorEnter': "பஸ் எண் மற்றும் கடவுச்சொல்லை உள்ளிடவும்.",
    'errorInvalid': "தவறான பஸ் எண் அல்லது கடவுச்சொல்.",
    'dashboardLabel': "டிரைவர் டேஷ்போர்டு",
    'busLabel': "பஸ் எண்",
    'statusLabel': "நிலை",
    'routeLabel': "பூந்தமல்லி வளாகம்",
    'gpsLabel': "நேரலை GPS நிலை",
    'latLabel': "அட்சரேகை",
    'lngLabel': "தீர்க்கரேகை",
    'accLabel': "துல்லியம்",
    'updatedLabel': "புதுப்பிக்கப்பட்டது",
    'highlightTitle': "உங்கள் பஸ் வளாக போக்குவரத்து நெட்வொர்க்குடன் இணைக்கப்பட்டுள்ளது.",
    'highlightText': "இடத்தை பகிர டிராக்கிங் தொடங்கவும்.",
    'startTracking': "டிராக்கிங் தொடங்கு",
    'stopTracking': "டிராக்கிங் நிறுத்து",
    'reportBreakdown': "பழுது எச்சரிக்கை",
    'fleetLabel': "நேரலை கடற்படை டேஷ்போர்டு",
    'etaTitle': "வழி வருகை நேரம் (ETA)",
    'nextStopLabel': "அடுத்த நிறுத்தம்:",
    'healthTitle': "வாகன ஆரோக்கியம்",
    'boardingTitle': "மாணவர் ஏறுதல்",
    'logBoarding': "ஏறுதல் பதிவு",
    'breakdownSection': "⚠️ பஸ் பழுது எச்சரிக்கை",
    'replacementBus': "மாற்று பஸ் எண்",
    'detectedLocation': "கண்டறியப்பட்ட இடம்",
    'sendAlert': "மாணவர்களுக்கு எச்சரிக்கை அனுப்பு",
    'langLabelDash': "மொழி",
    'logout': "வெளியேறு",
    'trackingStopped': "டிராக்கிங் நிறுத்தப்பட்டது.",
    'trackingStarted': "நேரலை GPS டிராக்கிங் தொடங்கப்பட்டது.",
    'boardingLogged': "மாணவர் ஏறுதல் பதிவு செய்யப்பட்டது.",
    'allBoarded': "அனைத்து மாணவர்களும் ஏற்கனவே ஏறிவிட்டனர்.",
    'replacementErrorEmpty': "மாற்று பஸ் எண்ணை உள்ளிடவும்",
    'locationUnavailable': "இடம் இன்னும் கிடைக்கவில்லை",
    'alertSaved': "✅ எச்சரிக்கை சேமிக்கப்பட்டது",
    'bottomInfo': "பனிமலர் பொறியியல் கல்லூரி வளாக போக்குவரத்து",
    'notifyRoute': "ஒரே வழியில் செல்லும் பேருந்துகளுக்கு அறிவிக்கவும்",
    'autoAlertNearby': "அருகிலுள்ள பேருந்துகளை தானாக எச்சரிக்கவும்",
    'notifyExpl': "உங்கள் பேருந்து பழுதடைந்தால், அதே வழியில் உள்ள மற்ற பேருந்துகளுக்கு தானாகவே அறிவிக்கப்பட்டு மாணவர்களை அழைத்துச் செல்லும்.",
    'sendBreakdownBuses': "பேருந்துகளுக்கு பழுது அறிவிப்பை அனுப்பு",
    'speechTitle': "பேச்சு மானிட்டர்",
    'speechWaiting': "டிராக்கிங்கிற்காக காத்திருக்கிறது...",
    'speechActive': "பேச்சு கண்காணிப்பு செயலில் உள்ளது.",
    'speakingTime': "பேசும் நேரம்",
    'sessions': "அமர்வுகள்",
    'longest': "நீண்ட நேரம்",
    'pctDrive': "% ஓட்டுநர் நேரம்",
    'speechUsage': "பேச்சு பயன்பாடு",
    'sessionLog': "அமர்வு பதிவு",
    'speechTooMuch': "⚠️ வாகனம் ஓட்டும்போது அதிகமாகப் பேசுகிறார் — நிர்வாகிக்கு அறிவிக்கப்பட்டது."
  },
  'te': {
    'appTitle': "డ్రైవర్ యాప్",
    'appSubtitle': "పనిమలర్ ఇంజనీరింగ్ కళాశాల",
    'langLabel': "భాషను ఎంచుకోండి",
    'sectionLogin': "డ్రైవర్ లాగిన్",
    'busNumber': "బస్సు సంఖ్య",
    'busPassword': "పాస్ వర్డ్",
    'signIn': "లాగిన్",
    'errorEnter': "బస్సు సంఖ్య మరియు పాస్ వర్డ్ నమోదు చేయండి.",
    'errorInvalid': "చెల్లని బస్సు సంఖ్య లేదా పాస్ వర్డ్.",
    'dashboardLabel': "డ్రైవర్ డాష్ బోర్డ్",
    'busLabel': "బస్సు సంఖ్య",
    'statusLabel': "స్థితి",
    'routeLabel': "పూనమల్లి క్యాంపస్",
    'gpsLabel': "లైవ్ GPS స్థితి",
    'latLabel': "అక్షాంశం",
    'lngLabel': "రేఖాంశం",
    'accLabel': "ఖచ్చితత్వం",
    'updatedLabel': "నవీకరించబడింది",
    'highlightTitle': "మీ బస్సు క్యాంపస్ రవాణా నెట్ వర్క్ తో అనుసంధానించబడింది.",
    'highlightText': "స్థానాన్ని పంచుకోవడానికి ట్రాకింగ్ ప్రారంభించండి.",
    'startTracking': "ట్రాకింగ్ ప్రారంభించు",
    'stopTracking': "ట్రాకింగ్ ఆపివేయి",
    'reportBreakdown': "బ్రేక్ డౌన్ నివేదించు",
    'fleetLabel': "లైవ్ ఫ్లీట్ డాష్ బోర్డ్",
    'etaTitle': "మార్గం ETA",
    'nextStopLabel': "తదుపరి స్టాప్:",
    'healthTitle': "వాహన ఆరోగ్యం",
    'boardingTitle': "విద్యార్థుల బోర్డింగ్",
    'logBoarding': "బోర్డింగ్ నమోదు",
    'breakdownSection': "⚠️ బస్సు బ్రేక్ డౌన్ అలర్ట్",
    'replacementBus': "ప్రత్యామ్నాయ బస్సు సంఖ్య",
    'detectedLocation': "గుర్తించిన స్థానం",
    'sendAlert': "విద్యార్థులకు అలర్ట్ పంపండి",
    'langLabelDash': "భాష",
    'logout': "లాగ్ అవుట్",
    'trackingStopped': "ట్రాకింగ్ ఆపివేయబడింది.",
    'trackingStarted': "లైవ్ GPS ట్రాకింగ్ ప్రారంభమైంది.",
    'boardingLogged': "విద్యార్థి బోర్డింగ్ నమోదైంది.",
    'allBoarded': "విద్యార్థులందరూ ఇప్పటికే బస్సు ఎక్కారు.",
    'replacementErrorEmpty': "ప్రత్యామ్నాయ బస్సు సంఖ్యను నమోదు చేయండి",
    'locationUnavailable': "స్థానం ఇంకా అందుబాటులో లేదు",
    'alertSaved': "✅ అలర్ట్ సేవ్ చేయబడింది",
    'bottomInfo': "పనిమలర్ ఇంజనీరింగ్ కళాశాల క్యాంపస్ రవాణా",
    'notifyRoute': "అదే మార్గంలో వెళ్లే బస్సులకు తెలియజేయండి",
    'autoAlertNearby': "సమీపంలోని బస్సులను ఆటోమేటిక్ గా అలర్ట్ చేయండి",
    'notifyExpl': "మీ బస్సు బ్రేక్ డౌన్ అయినప్పుడు, అదే మార్గంలో ఉన్న ఇతర బస్సులకు విద్యార్థులను తీసుకెళ్లడానికి ఆటోమేటిక్ గా తెలియజేయబడుతుంది.",
    'sendBreakdownBuses': "బస్సులకు బ్రేక్ డౌన్ అలర్ట్ పంపండి",
    'speechTitle': "స్పీచ్ మానిటర్",
    'speechWaiting': "ట్రాకింగ్ కోసం నిరీక్షణ...",
    'speechActive': "స్పీచ్ మానిటరింగ్ సక్రియంగా ఉంది.",
    'speakingTime': "మాట్లాడే సమయం",
    'sessions': "సెషన్లు",
    'longest': "అత్యధిక సమయం",
    'pctDrive': "% డ్రైవింగ్ సమయం",
    'speechUsage': "స్పీచ్ వినియోగం",
    'sessionLog': "సెషన్ లాగ్",
    'speechTooMuch': "⚠️ డ్రైవింగ్ చేస్తున్నప్పుడు ఎక్కువగా మాట్లాడుతున్నారు — అడ్మిన్ కు తెలియజేయబడింది."
  }
};
